# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myInsta' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myInsta
  pod 'Parse'
  pod 'AlamofireImage'

  target 'myInstaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myInstaUITests' do
    # Pods for testing
  end

end
